### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by guangzhao17** [znxlwm/UGATIT-pytorch#10]
run:
python main.py --dataset my_dataset --light True
error:
RuntimeError: CUDA error: out of memory

I had sucessfully installed pytorch with GPU on computer.
____________
import torch
torch.cuda.is_available()
True
____________
This works well,and I find no error when running other pytorch codes.

**Comment by znxlwm** [comment]
Above error means, your GPU memory is insufficient for training.

We trained model without light flag using V100 32GB, with light flag using 1080Ti 11GB.

Thank you

**Comment by t-k-** [comment]
Same error here, I solved it by setting a lower base channel number than the default one (via `--ch`).
