### ISSUE TITLE
Is there really anyone who have run through the pytorch-version codes?

### ISSUE THREAD

**Issue by JasonWeng8** [znxlwm/UGATIT-pytorch#45]
I don't have GPU on my laptop. So, I run the codes on the cloud(Google Drive). It always gives errors saying the gpu memory is not enough.

"cuda out of memory"

**Comment by VladAndronik** [comment]
It is possible only to use light version in Colab. I tried to increase the number of parameters. But for my task the results were unpleasant, it seems that only hard version works

**Comment by Lornatang** [comment]
@JasonWong97 @VladAndronik 
I've tried to make some changes to this code and it works. In the near future, I will present my pre training model.See https://github.com/Lornatang/UGATIT-PyTorch

**Comment by Lornatang** [comment]
![UGATIT](https://user-images.githubusercontent.com/31124350/82645644-c8936200-9c45-11ea-8c46-87b15fa855d1.png)

**Comment by GuoQuanhao** [comment]
> @JasonWong97 @VladAndronik
> I've tried to make some changes to this code and it works. In the near future, I will present my pre training model.See https://github.com/Lornatang/UGATIT-PyTorch

You have done a great work, so I want to know the what is the pytorch version you use

**Comment by Lornatang** [comment]
@GuoQuanhao PyTorch Version==1.5.
